### ISSUE TITLE
Exception in ASGI application

### ISSUE THREAD

**Issue by BluceLee2014** [bhaskatripathi/pdfGPT#71]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/lcserve/backend/gateway.py", line 1148, in __call__
    await self.app(scope, receive, custom_send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.8/site-packages/lcserve/backend/gateway.py", line 756, in _the_http_route
    return await _the_route(
  File "/usr/local/lib/python3.8/site-packages/lcserve/backend/gateway.py", line 678, in _the_route
    _func_data, _envs = _get_func_data(
  File "/usr/local/lib/python3.8/site-packages/lcserve/backend/gateway.py", line 585, in _get_func_data
    _func_data = json.loads(input_data)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by sesam** [comment]
What did you do to trigger this? Typically error reports need to include this information, so the developer can understand and try the same:

1. what steps did you take
2. **what happened** (the error above, but did anything else happen? Is this from the web or some console log? Maybe project developers can guess this, but for others participating here just adding a tiny bit more context helps!)
3. what did **you expect**  -- as there might be cases when you try to do something you expect should work, and developers or other users might know that it can only be done in some other way, or is a known issue, or not going to be supported.

Hope this helps! I'm participating on this ticket as I'd like to understand the issue myself and I'm looking for a way to get this project running locally on my Mac.
